-- The legacy import only carried ~19 commercial banks (bank_code values there are arbitrary legacy
-- internal codes, not real NIBSS codes, and are left exactly as-is). Everything added here uses the
-- real, publicly-published NIBSS institution code as bank_code - Nigerian commercial banks, merchant
-- banks, well-known microfinance banks, and the fintech/PSB operators members actually bank with today.
INSERT INTO banks (bank_code, name, sort_code) VALUES
  ('023', 'Citibank Nigeria', NULL),
  ('00103', 'Globus Bank', NULL),
  ('030', 'Heritage Bank', NULL),
  ('301', 'Jaiz Bank', NULL),
  ('107', 'Optimus Bank', NULL),
  ('104', 'Parallex Bank', NULL),
  ('105', 'Premium Trust Bank', NULL),
  ('101', 'Providus Bank', NULL),
  ('106', 'Signature Bank', NULL),
  ('068', 'Standard Chartered Bank', NULL),
  ('100', 'SunTrust Bank', NULL),
  ('102', 'Titan Trust Bank', NULL),
  ('302', 'Taj Bank', NULL),
  ('303', 'Lotus Bank', NULL),
  ('559', 'Coronation Merchant Bank', NULL),
  ('601', 'FBNQuest Merchant Bank', NULL),
  ('501', 'FSDH Merchant Bank', NULL),
  ('060', 'Nova Merchant Bank', NULL),
  ('502', 'Rand Merchant Bank', NULL),
  ('562', 'Greenwich Merchant Bank', NULL),
  ('090270', 'AB Microfinance Bank', NULL),
  ('602', 'Accion Microfinance Bank', NULL),
  ('090136', 'Baobab Microfinance Bank', NULL),
  ('090177', 'LAPO Microfinance Bank', NULL),
  ('070', 'NPF Microfinance Bank', NULL),
  ('090325', 'Sparkle Microfinance Bank', NULL),
  ('566', 'VFD Microfinance Bank (VBank)', NULL),
  ('50304', 'Mint Finex MFB', NULL),
  ('090551', 'Fairmoney Microfinance Bank', NULL),
  ('090515', 'Infinity Microfinance Bank', NULL),
  ('090121', 'Hasal Microfinance Bank', NULL),
  ('090175', 'Rubies Microfinance Bank', NULL),
  ('565', 'Carbon (One Finance) Microfinance Bank', NULL),
  ('50515', 'Moniepoint Microfinance Bank', NULL),
  ('50211', 'Kuda Microfinance Bank', NULL),
  ('100004', 'OPay (Paycom)', NULL),
  ('999991', 'PalmPay', NULL),
  ('50126', 'Eyowo', NULL),
  ('120001', '9 Payment Service Bank (9PSB)', NULL),
  ('120002', 'Money Master PSB', NULL),
  ('120003', 'Hope PSB', NULL),
  ('120005', 'MoMo PSB (MTN)', NULL)
ON CONFLICT (bank_code) DO NOTHING;
